Config = {}
Config.RP = true
Config.BotToken = "BOTUNUZUN TOKENİ"
Config.WebHook = "WEBHOOKUNUZ"
Config.ChannelID = "KOMUTLARIN İŞLEME ALINACAĞI KANAL"
Config.ReplyUserName = "GÖZÜKMESİNİ İSTEDİĞİN İSİM"
Config.AvatarURL = "GÖZÜKMESİNİ İSTEDİĞİN AVATAR"
Config.Prefix = "PREFİXİN"
Config.WaitEveryTick = 100  
